# Generated by Django 5.2.7 on 2026-01-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_city_country_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Телефонный код'),
        ),
    ]
