# Generated by Django 5.2.7 on 2026-01-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_owner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='main_produc_slug_354b31_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
