# Generated by Django 5.2.7 on 2026-01-26 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_category_slug_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_email_snapshot',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email автора (снимок)'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_name_snapshot',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя автора (снимок)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
