# Generated by Django 5.2.7 on 2026-01-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_review_author_email_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_name_snapshot',
            field=models.CharField(max_length=150, verbose_name='Имя автора (снимок)'),
        ),
    ]
