# Generated by Django 5.2.7 on 2026-02-01 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_review_author_name_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='operator',
        ),
        migrations.AddField(
            model_name='chat',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Оператор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('waiting', 'Ожидание'), ('closed', 'Закрыт')], default='open', max_length=16),
        ),
    ]
