# Generated by Django 5.2.7 on 2026-02-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_chat_operator_chat_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support_chat/%Y/%m/'),
        ),
    ]
